import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import FormCard from './FormCard';
import { useTranslation } from '@tailadmin/utils';
const FormList = ({ viewMode, currentForms, statusText }) => {
    const { t } = useTranslation();
    if (currentForms.length === 0) {
        return _jsx("div", { className: "py-8 text-center text-gray-400", children: t('form.history.empty') });
    }
    return viewMode === 'grid' ? (_jsx("div", { className: "grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4", children: currentForms.map((f) => (_jsx(FormCard, { form: f, statusText: statusText, t: t }, f.ID))) })) : (_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full text-sm text-left border", children: [_jsx("thead", { className: "bg-gray-50 dark:bg-gray-700/50 text-gray-500 dark:text-gray-400", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2", children: t('form.label.title') }), _jsx("th", { className: "px-4 py-2", children: t('form.label.description') }), _jsx("th", { className: "px-4 py-2", children: t('form.label.project') }), _jsx("th", { className: "px-4 py-2", children: t('table.status') }), _jsx("th", { className: "px-4 py-2", children: t('createdAt') })] }) }), _jsx("tbody", { children: currentForms.map((f) => (_jsxs("tr", { className: "border-t", children: [_jsx("td", { className: "px-4 py-2 font-medium text-gray-800 dark:text-white", children: f.title }), _jsx("td", { className: "px-4 py-2 text-gray-600 dark:text-gray-300", children: f.description }), _jsx("td", { className: "px-4 py-2", children: f.project?.ProjectName || '-' }), _jsx("td", { className: "px-4 py-2", children: _jsx("span", { className: `inline-block rounded-full px-2 py-0.5 text-xs font-semibold ${f.status === 'Completed' ? 'bg-green-100 text-green-800' : f.status === 'Rejected' ? 'bg-red-100 text-red-800' : f.status === 'Processing' ? 'bg-yellow-100 text-yellow-800' : 'bg-gray-100 text-gray-800'} dark:bg-opacity-20`, children: statusText(f.status) || f.status }) }), _jsx("td", { className: "px-4 py-2", children: new Date(f.CreatedAt).toLocaleDateString() })] }, f.ID))) })] }) }));
};
export default FormList;
