export declare const API_BASE_URL: string;
export declare const BASE_URL: string;
export declare const GET_NS_MONITORING_URL: (ns: string) => string;
export declare const LOGIN_URL: string;
export declare const REGISTER_URL: string;
export declare const LOGOUT_URL: string;
export declare const GROUPS_URL: string;
export declare const GROUP_BY_ID_URL: (id: number) => string;
export declare const USER_GROUP_URL: string;
export declare const USER_GROUP_BY_GROUP_URL: string;
export declare const USER_GROUP_BY_USER_URL: string;
export declare const CONFIG_FILES_URL: string;
export declare const CONFIG_FILE_BY_ID_URL: (id: number) => string;
export declare const CONFIG_FILE_RESOURCES_URL: (id: number) => string;
export declare const CONFIG_FILES_BY_PROJECT_URL: (id: number) => string;
export declare const RESOURCES_URL: string;
export declare const RESOURCE_BY_ID_URL: (id: number) => string;
export declare const PROJECTS_URL: string;
export declare const PROJECT_BY_ID_URL: (id: number) => string;
export declare const PROJECT_CONFIG_FILES_URL: (id: number) => string;
export declare const PROJECT_RESOURCES_URL: (id: number) => string;
export declare const PVC_CREATE_URL: string;
export declare const PVC_EXPAND_URL: string;
export declare const PVC_LIST_URL: (namespace: string) => string;
export declare const PVC_LIST_BY_PROJECT_URL: (pid: number) => string;
export declare const PVC_GET_URL: (namespace: string, name: string) => string;
export declare const PVC_DELETE_URL: (namespace: string, name: string) => string;
export declare const PVC_FILEBROWSER_START_URL: string;
export declare const PVC_FILEBROWSER_STOP_URL: string;
export declare const PROJECTS_BY_USER_URL: () => string;
export declare const USERS_URL: string;
export declare const USER_BY_ID_URL: (id: number) => string;
export declare const INSTANCE_URL: string;
export declare const INSTANCE_BY_ID_URL: (id: number) => string;
export declare const WEBSOCKET_MONITORING_URL: (namespace: string) => string;
export declare const WEBSOCKET_USER_MONITORING_URL: () => string;
export declare const USER_DRIVE_URL: string;
export declare const PROJECT_DRIVE_LIST: string;
//# sourceMappingURL=url.d.ts.map
